apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.1.201:6443
    token: <insert token>
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: <insert token>
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  name: oldie
  taints: null