apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>/</UrlBase>
    </Config>
  init-radarr.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /radarr-config/config.xml ]; then
      cp -n /init-radarr/config.xml /radarr-config/config.xml
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-radarr-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-config
data:
  PGID: "1000"
  PUID: "1000"