apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  type: NodePort
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      nodePort: 30400
      name: radarr-port
  selector:
    app: radarr