# Default values for Traefik
image:
  name: traefik
  # defaults to appVersion
  pullPolicy: Always

# Create a default IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: true

# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true

# Logs
# https://docs.traefik.io/observability/logs/
logs:
  # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
  general:
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    # To enable access logs
    enabled: true

ports:
  traefik:
    port: 9000
    hostPort: 9000
  web:
    port: 8000
    hostPort: 8000
  websecure:
    port: 8443
    hostPort: 8443