# Default values for Traefik
image:
  name: traefik
  # defaults to appVersion
  pullPolicy: Always

deployment:
  replicas: 3

# Create a default IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: true

# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true
# This should mount traefik directly to the host so it can function as a 
# reverse proxy for the server itself. Running it on each node will functionally
# created a pseudo-load-balancing reverse prox!
hostNetwork: true

# Logs
# https://docs.traefik.io/observability/logs/
logs:
  # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
  general:
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    # To enable access logs
    enabled: true
# nodeSelector: 
#   kubernetes.io/hostname: oldie
