kind: Deployment
apiVersion: apps/v1
metadata:
  name: unifi-controller
  namespace: monitoring
  labels:
    name: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: unifi-controller
  template:
    metadata:
      name: unifi-controller
      labels:
        name: unifi-controller
    spec:
      containers:
      - name: unifi-controller
        image: lscr.io/linuxserver/unifi-controller:latest
        ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 3478
            protocol: UDP
          - containerPort: 10001
            protocol: UDP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 1900
            protocol: UDP
        volumeMounts:
          - name: unifi-controller
            mountPath: /config
      volumes:
      - name: unifi-controller
        persistentVolumeClaim:
          claimName: unifi-controller
      nodeSelector:
        kubernetes.io/hostname: rainbow