kind: Service
apiVersion: v1
metadata:
  name: unifi-controller
  namespace: monitoring
  labels:
    app: unifi-controller
spec:
  type: NodePort
  selector:
    name: unifi-controller
  ports:
    - name: '8443'
      protocol: TCP
      port: 8443
      nodePort: 30201
    - name: '3478'
      protocol: UDP
      port: 3478
    - name: '8080'
      protocol: TCP
      port: 8080
      nodePort: 30200
    - name: '1900'
      protocol: TCP
      port: 1900
  