apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller
  namespace: monitoring
spec:
  storageClassName: "sdb-nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi