apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-unifi
spec:
  storageClassName: "" # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.2 # ip addres of nfs server
    path: "/volume1/nfs/unifi" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-unifi
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 8Gi