apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-config   # < name of the persistant volume claim ("pvc'")
  namespace: media         # < namespace where place the pvc
spec:
  storageClassName: "sdb-nfs-client"
  accessModes:
    - ReadWriteMany             # < Multiple pods can write to storage. Same value as pv
  resources:
    requests:
      storage: 5Gi              # < How much data can the pvc claim from pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-data
  namespace: media
spec:
  storageClassName: "sdc-nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1400Gi
